### ISSUE TITLE
Copied Schlage folder to custom componants. does not show up in add integration

### ISSUE THREAD

**Issue by ballison404** [mcnutter1/homeasssitant-schlage#16]
Ive followed the steps to install by copying the schlage folder and its contents into the custom-components folder that i already have and i restart HA...once it boots back up i go in settings -> devices ->add integration. searching for schlage comes up with nothing

**Comment by lewi3069** [comment]
Having the same issue.

**Comment by ricardo6677** [comment]
Same here =/
any step missing?

**Comment by ballison404** [comment]
this is related to the issue found at this link. https://github.com/mcnutter1/homeasssitant-schlage/issues/14 

problem is a comma at the end of line 10 in the manifest.json. that line should read

`    "version": "1.0"`
