### ISSUE TITLE
Heads up v2024.2.0 of HA will not start with this integration loaded

### ISSUE THREAD

**Issue by StephenShamakian** [mcnutter1/homeasssitant-schlage#23]
There is a thread going here: https://github.com/home-assistant/core/issues/109908 regarding the issue.

This integration came up as a culprit in my config and and another person's config. There is a diagnostic command (https://github.com/home-assistant/core/issues/109908#issuecomment-1933546153) that finds integration configs that have unique_id set incorrectly. This in turn is causing v2024.2.0 of HA to fail to start with this error: `TypeError: unhashable type: 'list'`

**Comment by mib1185** [comment]
it is caused by:
https://github.com/mcnutter1/homeasssitant-schlage/blob/bf739df4836c6e6be099fe2a602c171507fdd9bf/custom_components/schlage/config_flow.py#L23

**Comment by arsenal3008** [comment]
I understand that no one can enter 192.168.1.67:8123?

**Comment by StephenShamakian** [comment]
HA v2024.2.1 fixes the boot error (https://github.com/home-assistant/core/pull/109966) but now it outputs this error in the logs at HA startup:

`2024-02-09 09:38:04.093 ERROR (MainThread) [homeassistant.config_entries] Config entry 'Schlage Locks' from integration schlage has an invalid unique_id '['s****@s******t.com']', please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+schlage%22`

**Comment by dknowles2** [comment]
You should no longer need this custom integration. There is now native support for Schlage Encode locks built-in to Home Assistant. You can remove the custom integration, restart HA, and then set up Schlage through the normal "Add Integration" flow.

**Comment by StephenShamakian** [comment]
Thanks again! I moved to the official integration and it seems to work!

Maybe it might be good to add a note to the readme on this repo that it is no longer needed? That is if the owner of this repo is still active doesn't seem like it.

Closing Issue.
